// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	DeleteJob(ctx context.Context, id int64) error
	GetJob(ctx context.Context, id int64) (Job, error)
	ListJobs(ctx context.Context) ([]Job, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
